# Generated by Django 4.0.1 on 2022-02-01 20:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EDL',
            fields=[
                ('name', models.CharField(help_text='EDL name', max_length=100)),
                ('slug', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'edls',
            },
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP Address of the device')),
                ('name', models.CharField(help_text='Hostname', max_length=100)),
                ('expiration_date', models.DateTimeField(help_text='Expires at')),
                ('edl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='edlprovider.edl')),
            ],
            options={
                'db_table': 'ip_addresses',
            },
        ),
    ]
